export enum MemberSortEnum {
  DISPLAY_NAME_ASC = "DISPLAY_NAME_ASC",
  DISPLAY_NAME_DESC = "DISPLAY_NAME_DESC",
  EMAIL_ASC = "EMAIL_ASC",
  EMAIL_DESC = "EMAIL_DESC",
  LAST_SEEN_ASC = "LAST_SEEN_ASC",
  LAST_SEEN_DESC = "LAST_SEEN_DESC",
  ROLE_ASC = "ROLE_ASC",
  ROLE_DESC = "ROLE_DESC",
}
