query GetAdminRole($userId: uuid = "") {
  user_club_relation(
    where: { role: { _eq: ADMIN }, user_id: { _eq: $userId } }
  ) {
    role
  }
}

fragment OwnUser on users {
  avatarUrl
  displayName
  email
}

query GetUserById($userId: uuid!) {
  users(where: { id: { _eq: $userId } }) {
    ...OwnUser
  }
}
